### ISSUE TITLE
when available_images is invalid it calls self.options["image"] which doesn't exist

### ISSUE THREAD

**Issue by rbuusnielsen** [rasmunk/corc#1]
https://github.com/rasmunk/corc/blob/2f58dfec7b3188c5260763b082623a09ba8dff99/corc/providers/oci/cluster.py#L529
https://github.com/rasmunk/corc/blob/2f58dfec7b3188c5260763b082623a09ba8dff99/corc/providers/oci/cluster.py#L536

**Comment by rasmunk** [comment]
Thank you for reporting this issue, have addressed it in https://github.com/rasmunk/corc/commit/a100be2d9a648afcfb07b81526b30630567ec97c
